# docker-compose.yml
services:
  yt-downloader:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./cookies.txt:/app/cookies.txt
    env_file:
      - .env
    restart: unless-stopped
    